### ISSUE TITLE
pretrain error

### ISSUE THREAD

**Issue by yhjiujiu** [DeepGraphLearning/ULTRA#12]
Thanks for your wonderful work, when i pretrain the model using the following command ： python script/pretrain.py -c /path/to/config/transductive/pretrain_3g.yaml --gpus [0] , but  there is a problem.
![dfa1914a4adfddbd6e33247130ddb519](https://github.com/DeepGraphLearning/ULTRA/assets/39623606/55855b02-fce8-4178-b9e7-e04f5a86d9a0)
 and my versions of all packages are following:
![cc86c1dff8c094b8f3cbeefdbd5a6469_720](https://github.com/DeepGraphLearning/ULTRA/assets/39623606/d5a67dee-c68d-4bd4-87e4-82586512addf)

**Comment by migalkin** [comment]
Could you please post the full stack trace of the `ninja` error? 
Without it, the only suggestion is that you don't have a C++ compiler installed - so make sure you have one

**Comment by yhjiujiu** [comment]
Thanks for your answer. I checked there is a C++ compiler.  
![a67b5d4d6321bf1e7ad8c16c83cf537f](https://github.com/DeepGraphLearning/ULTRA/assets/39623606/8f720373-3e83-48bc-b15c-bc2b13a71d9e)
And the full stack trace are as follows: 
![345ddecebe8974a5505da3d1acbedda8](https://github.com/DeepGraphLearning/ULTRA/assets/39623606/2050f650-8407-4704-b5f9-c18b839bdbce)
![46cf8ad213de6fb37baad9045f8828ea](https://github.com/DeepGraphLearning/ULTRA/assets/39623606/545f64b9-87d9-4e12-8244-deeccb86a02b)

**Comment by migalkin** [comment]
Ah you are missing the `nvcc` package for compiling CUDA kernels. Looks like you are on the lab machine with A6000 - if you have some module environment, try loading the full CUDA toolkit for cuda12, not just the runtime. 
Alternatively, install `cuda-nvcc` matching your cuda version from [conda](https://anaconda.org/nvidia/cuda-nvcc) or [conda-forge](https://anaconda.org/conda-forge/cuda-nvcc).
