### ISSUE TITLE
Names of databases for training ultra_50g.pth

### ISSUE THREAD

**Issue by hnguyentt** [DeepGraphLearning/ULTRA#15]
Hello team,

Thank you for your excellent work! I used your `ultra_50g.pth` to do the inference (zero-shot learning) on my own dataset with the purpose to find the new links between entities. I evaluated the predicted new links by comparing them with the scientific papers and found the new predicted links very accurate. This is really amazing to me!

However, I am wondering that  because `ultra_50g.pth` has been trained on 50 graphs that contained those links and it remembered them to transfer to my own dataset or not. Therefore, could you please share the database names used in training `ultra_50g.pth` checkpoint so that I can check this? I didn’t see this information in your paper nor GitHub repo.

Thank you very much again for this really innovative work!

Best,
Hoa

**Comment by migalkin** [comment]
Sure, here is an excerpt from the pre-training config:

```yaml
[FB15k237, WN18RR, CoDExMedium, NELL995, 
  YAGO310, DBpedia100k, AristoV4, Hetionet,  
  WDsinger, CoDExSmall, NELL23k, ConceptNet100k, FB15k237_10,  # 13 transductive datasets
  FB15k237Inductive:v1, FB15k237Inductive:v2, FB15k237Inductive:v3, FB15k237Inductive:v4,
  WN18RRInductive:v1, WN18RRInductive:v2, WN18RRInductive:v3, WN18RRInductive:v4,
  NELLInductive:v1, NELLInductive:v2, NELLInductive:v3, NELLInductive:v4,
  ILPC2022:small, ILPC2022:large,  # 14 inductive entity datasets 
  FBIngram:25, FBIngram:50, FBIngram:75, FBIngram:100,
  WKIngram:25, WKIngram:50, WKIngram:75, WKIngram:100,
  NLIngram:0, NLIngram:25, NLIngram:50, NLIngram:75, NLIngram:100,
  WikiTopicsMT1:tax, WikiTopicsMT1:health, WikiTopicsMT2:org, WikiTopicsMT2:sci,
  WikiTopicsMT3:art, WikiTopicsMT3:infra, WikiTopicsMT4:sci, WikiTopicsMT4:health,
  Metafam:None, FBNELL:None] # 23 inductive entity & relation datasets
```

All of those graphs are presented in the main paper and are mostly subsets of Freebase, Wikidata, and NELL with some mix of WordNet, YAGO, DBpedia, AristoV4, Hetionet, ConceptNet
