### ISSUE TITLE
Why is nnz set as edge_index.size(0) in rspmm.cpp?

### ISSUE THREAD

**Issue by cold-blue** [DeepGraphLearning/ULTRA#16]
I read the code of rspmm.cpp and find the meaning of nnz should be the whole edge number. So why isn't nnz set as edge_index.size(1)?
Is that an error of code?
![image](https://github.com/DeepGraphLearning/ULTRA/assets/21053269/f4b9f575-f9ce-4c21-a882-cc984c11301e)
I find the last node can't be updated due to this bug.

**Comment by migalkin** [comment]
Good catch, thanks for noticing - we also stumbled upon the same problem (incorrect node state for the very last node) in another workstream. PR #17 fixes the issue - I ran some tests and now results are correct
