### ISSUE TITLE
Error in running the example

### ISSUE THREAD

**Issue by faren-f** [DeepGraphLearning/ULTRA#4]
When I run the example you provided 

```
python script/run.py -c config/transductive/inference.yaml --dataset CoDExSmall --epochs 0 --bpe null --gpus null --ckpt ckpts/ultra_4g.pth
```
I get the error below:
**FileNotFoundError: [Errno 2] No such file or directory: 'ckpts/ultra_4g.pth'**

The error goes away when I replace ```config/transductive/inference.yaml``` with ```config/transductive/pretrain_4g.yaml```, but then I get a new error:

**IndexError: range object index out of range**
Could you please resolve this issue?

**Comment by migalkin** [comment]
There is already existing and solved issue #3 on that - please use the full path to the checkpoint.

For inference, you do _not_ need the pretraining config, please use the `inference.yaml` of appropriate type (transductive / inductive depending on the dataset)

**Comment by faren-f** [comment]
Thank you so much for your response, the problem is solved! 
I was wondering if you could also help me by answering my question. 
I have my own custom graph including nodes and edges different from your 57 training datasets. Am I only restricted to using inductive inference (as both nodes and edges are new) or the transductive inference is also possible for me? If so what is the difference?

**Comment by migalkin** [comment]
Depends on the validation/test sets of your custom graph:
* Transductive - you have one graph with a fixed set of nodes and relation types, your validation and test set edges are based on this one graph and share the same set of nodes and relations. 
* Inductive - you have one training graph and a different one for validation/test.

**Comment by faren-f** [comment]
So, if I undretood correctly, the difference between Transductive and Inductive metters when we do "fine tuning", and for zero-shot inference there shoudn't be any difference, and we no longer need any traning dataset in zero-shot. Do I have a right impression?

**Comment by migalkin** [comment]
Conceptually, in the zero-shot case, there is indeed almost no difference.
Practically, in the codebase we do differentiate between the setups based on the _inference_ graph - the graph based on which you run evaluation.

* In the transductive setup, training graph = inference graph, that is, even if you run zero-shot inference, you still load the main graph, and predict edges based on this graph. 
* In the inductive setup, training graph != inference graph, and the zero-shot inference will run evaluation on the inference graph.

I don't know about your setup but if you have only one fixed graph you want to run inference on, I'd suggest trying the transductive setup

**Comment by faren-f** [comment]
Thanks, I got the point. Your explanation was awesome!
The last question and just to make sure, in inductive inference, are test graph and validation graph subsets of inference graph?

**Comment by migalkin** [comment]
We should distinguish between validation/test _edges_ and inference _graph_ - usually, we are given some graph (inference graph) based on which we are predicting validation/test edges. 

If you look into the [InductiveDataset creation procedure](https://github.com/DeepGraphLearning/ULTRA/blob/f159e556fc4a77f20e9a3823f8a251eabbc075b6/ultra/datasets.py#L680), validation and test graphs usually share the same base edge index (the inference graph we are talking about here), but have different `target_edge_index` - the actual triples to predict.

Having said that, there are some nuances in different datasets (eg, in some, validation edges are based on the training graph, but test is on the unseen inference graph), but for simplicity let's assume that validation/test objects have the same underlying inference graph

**Comment by faren-f** [comment]
Perfect! Thanks a lot for your quick and comprehensive response :-)
