### ISSUE TITLE
ULTRA on HuggingFace Hub

### ISSUE THREAD

**Issue by migalkin** [DeepGraphLearning/ULTRA#6]
Hi @clefourrier, you helped us some time ago to put LRGB on 🤗 Datasets, so you seem the only person from HF who has any remote experience with Graph ML although we know you are into LLM leaderboards recently  :)

We tried to put ULTRA checkpoints on the Hub here https://huggingface.co/mgalkin with the basic write-up and code examples. Could you please have a look to check whether graph models are ok in this format on the Hub?

A few caveats at the moment: 
* Model repos on the Hub pack most of the code from this repo and have additional interfaces `UltraConfig` and `UltraLinkPrediction`
* I can only wrap those into `AutoConfig` and `AutoLinkPrediction` locally, I presume that Auto interfaces will recognize Ultra website-wide only if we implement it directly in Transformers?

**Comment by clefourrier** [comment]
Hi! 
Thanks a lot for your work! From a first glance it looks good, well done!

Regarding point 1, I think it's OK for now! 

Regarding point 2: I think you could use the "auto_map" argument in your config to make your model/config loadable with `AutoConfig.from_pretrained(model_path, trust_remote_code=True)`. 
```
"auto_map": {
    "AutoConfig": "modeling.UltraConfig",
    "AutoModel": "modeling.UltraForKnowledgeGraphReasoning",
}
```

Integrating models in `transformers` is done depending on usage, so for new models, we definitely recommend starting with a hub addition, just like you did.

**Comment by clefourrier** [comment]
cc @ArthurZucker for potential additional input

**Comment by migalkin** [comment]
Thanks @clefourrier, `AutoModel` works now! 

1. Added the `auto_map` dict to the `UltraConfig` in `modeling.py` (eg, here https://huggingface.co/mgalkin/ultra_50g/blob/main/modeling.py) and to `config.json` 
2. The following line is working now
```python
model = AutoModel.from_pretrained("mgalkin/ultra_50g", trust_remote_code=True)
```
