### ISSUE TITLE
Torch install instructions may be invalid

### ISSUE THREAD

**Issue by JoshuaPurtell** [DeepGraphLearning/ULTRA#8]
(custom_env) me@MY-MBP ULTRA % pip install torch==2.1.0 --index-url https://download.pytorch.org/whl/cu118
Looking in indexes: https://download.pytorch.org/whl/cu118
ERROR: Could not find a version that satisfies the requirement torch==2.1.0 (from versions: none)
ERROR: No matching distribution found for torch==2.1.0

**Comment by migalkin** [comment]
Are you running it on a macbook? If so, CUDA won't work and you'd rather install a CPU version with `pip install torch`
